### ISSUE TITLE
Move gender to optional section and define gender terms in dropdown

### ISSUE THREAD

**Issue by jmcmurry** [TheJacksonLaboratory/PhenopacketLab#148]
These terms would benefit from hover-over description or an info button.
I would also expect to see cis-gender in the menu

<img width="489" alt="Screenshot 2023-03-14 at 1 58 40 PM" src="https://user-images.githubusercontent.com/3658863/225134719-8b72492e-9338-49ba-901e-3ba811c1c04e.png">

**Comment by pnrobinson** [comment]
@jmcmurry We were thinking of removing the gender widget, since we want to keep things relatively simple for the user and gender is probably of lesser importance in many rare disease research use cases. Possibly we could keep it as an option that is partially hidden and clearly optional. Also, we would use the gender terms as recommended on the phenopacket schema website

**Comment by jmcmurry** [comment]
I agree simplicity is really important. Maybe there's a section where we can park several such options?

**Comment by belkassaby** [comment]
Hi Peter, Julie, here are screenshots of the updated UI (not deployed yet) following your advice. For the list of genders, @ielis and I picked the GSSO ontology with the default ones available there. As it seems the terms on the phenopacket documentation are not there : the Gender property is an OntologyClass (as opposed to Sex and KaryoptypicSex which are enums).
![Screen Shot 2023-03-16 at 4 19 37 PM](https://user-images.githubusercontent.com/1378819/225743541-a1749d39-7d41-411b-b173-4879743c34bd.png)
![Screen Shot 2023-03-16 at 4 20 03 PM](https://user-images.githubusercontent.com/1378819/225743549-d36a6cba-a698-483d-a96b-ad6f1b2ccf9d.png)

**Comment by jmcmurry** [comment]
This is an improvement but is cisgender on the list? I also want to make sure that this is an optional field.

**Comment by jmcmurry** [comment]
Alternatively, this could be free text; I don't know that you are going to capture enough nuance to satisfy everyone

**Comment by pnrobinson** [comment]
The field is an ontology class. This is what we are recommending -- 
http://phenopackets.org/phenopacket-tools/constants.html#gender
This does not provide all nuances of course and if people need more they will need to choose another ontology.
I think we should not show this field now, because gender is not of much relevance for genomic research at the moment and it is better to focus on things we need for our use case than to offer all possible options.

**Comment by belkassaby** [comment]
@jmcmurry yes i think cisgender was in that list, but somehow its label was "na-trans". no idea why. Might have been an error in the GSSO ontology. 
I will remove the gender field for now (just commented in the code so it will be easier to re-implement when needed).

**Comment by BethSundberg** [comment]
Tested and looks good
