### ISSUE TITLE
Repeated field elements cannot be null in field: org.phenopackets.schema.v2.core.MetaData.resources

### ISSUE THREAD

**Issue by pnrobinson** [TheJacksonLaboratory/PhenopacketLab#189]
This error occurs after I have entered data for a phenopacket

InputValidator] Data format validator	input	com.google.protobuf.InvalidProtocolBufferException: Repeated field elements cannot be null in field: org.phenopackets.schema.v2.core.MetaData.resources

**Comment by BethSundberg** [comment]
I am not able to recreate this error.

**Comment by BethSundberg** [comment]
@belkassaby I have found an instance of this error:


![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/ab444378-d8d4-4adb-b667-f8cc324e0971)

I uploaded the example file: bethlem-myopathy-detailed.json. It had a lot of metadata errors, the suggestion to fix those worked. However, this one error is left. Can you tell what is null that should not be??

**Comment by BethSundberg** [comment]
@belkassaby I just checked and this error occurs the same way on both dev and sqa sites.

**Comment by belkassaby** [comment]
This seems to be due to some already created phenopacket with a term not recognized by the validator, and/or the resource in the phenopacketlab backend not being found for that term. So the prefix of the term not found would be an ontology prefix not in phenopacketlab (CARO for instance for "Common Anatomy Reference Ontology") and the corresponding resource set in the phenopacket is undefined therefore when validating, the validator returns this error. I would need to somehow better manage the warning/error message so the user knows that..

**Comment by pnrobinson** [comment]
@belkassaby 
This should not happen with phenopackets we create, right? It might happen if somebody uploads a phenopacket? I do not understand where the CARO prefix is coming from?

**Comment by belkassaby** [comment]
@pnrobinson Yes this shouldn't happen with a phenopacket created through phenopacketlab. But it might happen with a phenopacket created elsewhere, (the CARO prefix is just an example i picked and if that prefix and id was found in a phenopacket (which it wouldn't because we dont have any property in a phenopacket that could have such a term from that ontology). The error will just be thrown if the file is validated after having been updated. So the user still can edit their file in the UI. It's just the validation that will return this result.

**Comment by BethSundberg** [comment]
As I understand it, we are ignoring this error if it is caused by a phenopacket that was created elsewhere. I have not found this error on a phenopacket I have created. I'm going to mark this as done.
