### ISSUE TITLE
Bug: Several problems with step 1: Individual information

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#191]
When entering individual information in create a phenopacket step1, the following bugs/issues/suggestions were found. See the list in the attached word document.

[Phenopacket new issue suggestions June 2023.docx](https://github.com/TheJacksonLaboratory/PhenopacketLab/files/11708930/Phenopacket.new.issue.suggestions.June.2023.docx)

**Comment by belkassaby** [comment]
List of Bug/enhancement found
- [ ] save whether the "I confirm that this ID is not a medical record..." has already been selected if going back in the stepper process
- [ ] Rare disease 
- [ ] Sex not saved properly (see #175)
- [ ] Age range bug1: max end days not correctly set for upper edge case (what is saved is the input of the user if days>31)
- [ ] Age range bug2: end age that is less than start age is acceptable, it shouldn't ? @ielis 
- [ ] Gestational age : edge cases not correctly set/saved (if more than 42 weeks is entered, 42 should be the value set), same for days. of more than 7 days.)
- [ ] Age at last clinical encounter not saved in phenopacket
- [ ] Gender and alternate field are saved in the phenopacket although they are not in the UI

**Comment by ielis** [comment]
Re: age range bug 2 - Yes, I totally agree. The start must not be after the end, and I would argue that not even at the end (use Age instead). However, the implementation must take into account several issues. Suppose an element from the set `{'P29D', 'P30D', 'P31D'} and `P1M`. Which one is greater? It depends how many days there are in a month. We may need to agree upon some heuristics.

Re: max survival time - the number of days can be complicated. The users may not have the right number all the time, e.g. for survival of 5 years 3 months and 2 days. The issue is similar to the one above - how many days are there in a month? The survival time in days can be calculated using a difference of two local dates with the first being the date of diagnosis and the second the time of death. You would need to add a small widget that has two tiny calendars, where the user selects the local dates in a similar way we search for flights (see below). Otherwise, I do not see how this can be done..
![image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/12170955/96715d52-a5f1-4fb3-ad73-ffd96dacf898)

**Comment by pnrobinson** [comment]
One thing is that if somebody needs to use AgeRange it is because they need to preserve privacy. Therefore, they will not be using a Web-based app. Given the amount of other things we need to do, I think we should remove the AgeRange option from the App for now because I do not think anybody will use it in this setting!
