### ISSUE TITLE
Deleting a feature, disease, interpretation on a phenopacket doesn't remove it

### ISSUE THREAD

**Issue by belkassaby** [TheJacksonLaboratory/PhenopacketLab#248]
After deleting a feature, disease interpretation from a phenopacket, closing the phenopacket tab, reopening it will show these feature, disease, interpretation previously deleted. The deletion is not working properly.

**Comment by belkassaby** [comment]
this bug seems to be the same for all elements of a phenopacket. (medical actions, measurements, biosamples etc)

**Comment by BethSundberg** [comment]
@belkassaby The deletion is now working. However, when I delete a disease it is asking me twice to confirm the deletion. It asks me once as expected. Then, when I leave that phenopacket to look at another one I get a second deletion confirmation request. It does not matter if I choose the "No" option since it is already deleted. I believe it is only disease that is doing this.



![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/91597cb3-c548-4081-87a4-9203cebb17b0)

**Comment by belkassaby** [comment]
@BethSundberg https://github.com/TheJacksonLaboratory/PhenopacketLab/pull/254 should fix this

**Comment by BethSundberg** [comment]
This is now working properly on the dev site.
