### ISSUE TITLE
Initial attempts to save a persistent change do not work

### ISSUE THREAD

**Issue by BethSundberg** [TheJacksonLaboratory/PhenopacketLab#277]
Initial attempts to save a change do not work. Later they will work, this seems to happen with a clean sheet - I deleted all phenopackets, logged out, cleared history, and closed browser.

To reproduce: uploaded one of the example phenotypes. Added a new phenotypic feature. When I saved it I got red message that it was not saved (obviously to disk only). It does appear in the list, in this screen shot it is the last one for "alopecia".

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/d902e228-7789-45cc-922b-0615c8d9549a)

It got a 400 bad request error

![Image](https://github.com/TheJacksonLaboratory/PhenopacketLab/assets/11503959/de63152f-2130-4e96-bd36-69f7bb86ac7c)

**Comment by BethSundberg** [comment]
I get this same error when trying to do the validation and have it save the metadata

**Comment by BethSundberg** [comment]
If I simply close my browser and re-open, everything works fine. My changes are saved. Note of course that I stayed logged on and the phenopacket is immediately shown on the screen.

**Comment by belkassaby** [comment]
Thanks for recreating this bug Beth! I found out the reason why : the first time around a phenopacket is uploaded to the DB, the phenopacket in question that is added on the frontend side doesnt have a db ID (the save endpoint would just return true or false instead of the entity saved). Now it is returning the entity, if no error, and therefore the corresponding dbID with it. Then when we do an update on the phenopacket uploaded we have the dbID and therefore no error 400 with an id=undefined... It was working if you would upload a phenopacket then reload the page (as then the frontend would call the get endpoint that returns a list of phenopacket that has db ID s associated with each of them.) im redeploying dev so you can test this out.

**Comment by BethSundberg** [comment]
It is working now.
